### ISSUE TITLE
OWASP M2 Insecure data Storage : App stores passkey in plaintext under the keychain.

### ISSUE THREAD

**Issue by bugwrangler** [MiniKeePass/MiniKeePass#353]
Step to reproduce :- 

1. Getting access to the file system.
2. Coping keychain access script to file system (https://github.com/ptoomey3/Keychain-Dumper)
3. Execute script which reveals stored accounts and secret
4. you will see your App Pin stored in the plain text. 

Actual Result :-  The results show that a lost iOS device may endanger also the confidentiality of data that is not stored on the device, but which is accessible for an attacker via the revealed stored secrets. 

Expected result :- Pin should be stored in HASH or dynamic SALT which is addition security layer.

Notes:- keychain is only available when the phone lock has been broken. Now - According to Lookout Mobile security - 3.1 million phone were lost last year. Now – Question here is about the credibility of Application security when the phone gets lost. 
  
Keychain snip  :-

Generic Password
----------------
Service: com.jflan.MiniKeePass.pin
Account: PIN
Entitlement Group: 4BWNF7HW3R.com.jflan.MiniKeePass
Label: (null)
Generic Field: (null)
Keychain Data: [XXXXXXXXXXXXXX] - PlainText 

![poc1](https://cloud.githubusercontent.com/assets/6933052/5893838/32f69efc-a519-11e4-99f0-8e3aae20b1e7.png)

**Comment by BasicXP** [comment]
A PIN-code is just 4 digits long, there is no point in hashing it, since bruteforcing 10000 possible values is a matter of seconds on modern computers.

**Comment by bugwrangler** [comment]
Aha so. I guess there is no need to pin feature #Usability

**Comment by jarush** [comment]
1.6 uses PBKDF2 to secure the PIN that's stored in the keychain.
