### ISSUE TITLE
Compatibility with Keeppass2Android?

### ISSUE THREAD

**Issue by annjannj** [MiniKeePass/MiniKeePass#362]
We have android mobile phones and laptops with keeppass2Android installed and they reference a shared password file on Dropbox.   Minikeeppass is set up to reference that same database file on Dropbox but is not apparently getting updates when changes are made on Keeppass2Android on the android/pc devices.  Any suggestions?  Thank you!

**Comment by annjannj** [comment]
oops minikeeppass is set up on my IPAD- forgot to mention that important point!

**Comment by Forst** [comment]
You need to manually open file in Dropbox every time it's updated in order for the changes to be visible.

**Comment by annjannj** [comment]
Thank you Foster.  I apologize for asking a question that was clearly
documented!  I just noticed it.    Curious why this is not possible because
it makes it cumbersome to use?

Thanks again!

Ann

**Comment by Forst** [comment]
@annjannj The way it works now is indeed very simple and uses the standard means of iOS to work with files, which allows to use many apps that support the same method.

**Comment by annjannj** [comment]
Oh, I see.  Thank you!
