### ISSUE TITLE
Minikeepass entries showing up in IOS predictive keyboard

### ISSUE THREAD

**Issue by rubalo** [MiniKeePass/MiniKeePass#375]
Hi guys,

Amaizing app ! One remark though, I noticed that entries are showing up in IOS predictive keyboard. Not so secure Hein ;-). I turned the functionnality off and reseted the keyboard but It might be good to have it turned off inside the app if it is possible.

Thanks for your great work.

\J

**Comment by jarush** [comment]
Good catch... this hadn't really crossed our minds as a possibility.  I fixed it in code by turning off autocorrect for most of the text fields, which should disable the predictive keyboard from learning words.

**Comment by rubalo** [comment]
Thanks !
