### ISSUE TITLE
Security issue with new Touch ID support

### ISSUE THREAD

**Issue by gitbls** [MiniKeePass/MiniKeePass#377]
THANK YOU for adding Touch ID support. It's a massive ease of use improvement. 

BUT, there appears to be a significant issue with it at the moment. If I click "cancel" to the Touch ID prompt, the keypad to enter my PIN flashes briefly on the screen. And then I'm into the database list, and able to browse and read all the entries.

**Comment by jarush** [comment]
We'll take a look at it! Thanks for reporting the issue.

**Comment by gitbls** [comment]
Thanks. Now on a real computer where I can type more. I had a PIN with timeout on the app, and when i upgraded to the newest version, it automatically prompted for Touch ID. I haven't tried unsetting and resetting the lock and timeout values, but a straight upgrade in what I would guess is a common configuration leaves the database exposed. Let me know if you need any additional information.

**Comment by RobTiki** [comment]
@gitbls.  
Sound like its the timeout setting.  I have my timeout set to immediately.  I am not having that issue.  I use a pin and a long password on my db.  Below is my info.

iphone 6
ios 8.2
latest version of minikee

**Comment by jarush** [comment]
I've reproduced some odd behavior:
* Cancel right away, shows the pin screen. Good. 
* Use wrong finger, cancel, shows the pin screen. Good. 
* Use correct finger, asks a second time, cancel, let's you into app. This shouldn't happen.

Can anyone else confirm this is similar to what they've seen?

**Comment by RobTiki** [comment]
Jarush,

Are you saying that you get prompted for touchid a second time when you use the CORRECT finger?
Correct finger lets me into app.  When I select a DB I get prompted for the db password.

I can confirm that bullet point 1 & 2 is true.

**Comment by jarush** [comment]
@RobTiki - that's what a friend of mine was seeing. I actually don't have a TouchID device.  They get prompted for TouchID twice every time for some reason. 

We didn't see anything like this during beta testing, but there seems to be some weird bug in there.

**Comment by RobTiki** [comment]
@jarush ,

Do you have any details on your friends info? iOS version, iphone version etc.  I am not having any of the reported issues.

**Comment by jarush** [comment]
iPhone 5S. Not sure about iOS version. I'll check tomorrow and see if I can also track down the bug when I have the opportunity to connect his iPhone to my laptop.

**Comment by jarush** [comment]
I have another friend with a iPhone 6, iOS 8.3, and everything seems to work correctly. No odd behavior.

**Comment by gitbls** [comment]
I set the Lock Timeout to Immediately, which is probably what it should be with Touch ID enabled, and things are working correctly.  I'm not seeing the issue that jarush reported (Use correct finger, asks a second time, cancel, let's you into app. This shouldn't happen.).

But, I have seen another scenario that's not correct: Cancel touch ID, then on the PIN screen close the app (single button click). When I open the app again it goes to the PIN screen, not to the Touch ID screen. Continues to do that until PIN code successfully entered.

Good news is that it's not a security hole.

**Comment by jarush** [comment]
Once it shows the pin screen, that'll persist even if you background the app. It will probably prompt you for TouchID again if you were to kill the app and reopen though.

**Comment by gitbls** [comment]
@jarush Fair enough. Saw your comment and verified that Dropbox does the same thing.

So, the key issue is for people who have the older version of the app with a non-Immediately timeout, and then upgrade to the new version with Touch ID. They're exposed until they change their Lock Timeout to Immediately or a future fixed version.

**Comment by N-L-P** [comment]
Adding: If a user does not have Touch ID enabled (iPhone 6, iOS 8.3), the PIN can be completely bypassed, for example, by double-tapping the Home Button, then immediately retouching the app screen to return to it.

@gitbls The key issue still appears to be what you point out above: this occurrs on upgrade to MiniKeePass 1.6 with a non-Immediately Lock Timeout.  (Mine was overwrote and set to 30 seconds on upgrade.)

**Comment by jarush** [comment]
@N-L-P - Thanks for the report about the double-tap home.  I pushed a fix for this bug.

**Comment by jarush** [comment]
There seemed to be a timing problem with presenting TouchID and getting the TouchID auth status on some devices (which ended up letting you cancel sometimes).  I believe I have a fix in commit d6c47c2, and if testing shows there's no problems we'll get it submitted to the App Store ASAP.

**Comment by marcoanonimo** [comment]
This update introduce the login with Touch ID. 
Good vero well donde, but unfortunately this has introduced a big bug that allow to pass through the PIN or Touch ID authentication. How to reproduce:
1. Go to setting of the app and put the 'Lock Timeout' to 30 seconds 
2. Close the app and wait longer than 30 seconds
3. Reopen the app and cancel Touch ID authentication (if is enabled in the setting) or click on the home button (if Touch ID is not enabled in the setting)
4. Now you are logged in without the PIN or Touch ID 

The problem does not occur if in the setting of the app the 'Lock Timeout' is immediately.

Please fix this major and critical bug, thanks!

Marco

**Comment by marcoanonimo** [comment]
Minikeepass 1.6
Iphone 5S
IOS 8.2

**Comment by darren12345** [comment]
Just wanted to leave my 2p worth. I have timeout set to 30 seconds and about 50% of the time I can hit cancel on the TouchID prompt and get straight into the database without entering the PIN. iPhone 5s/iOS 8.3. Thanks.

**Comment by darren12345** [comment]
Actually, it's pretty much every time.

**Comment by jarush** [comment]
Thanks for everyone providing feedback. We fixed the bug early last week and submitted a new build to Apple. Still waiting on their approval.

**Comment by jarush** [comment]
Version 1.6.1 is in the store now and addresses this issue, as well allows for arbitrary length alphanumeric PINs using the new "A-Z" button on the PIN screen.

**Comment by jarush** [comment]
Anyone still having issues with the pin screen/TouchID?

**Comment by darren12345** [comment]
Not me, fix works fine. Thanks.

**Comment by gitbls** [comment]
No. The issues I was having are corrected. Thanks for the update!

**Comment by marcoanonimo** [comment]
It's OK now, Thanks
