### ISSUE TITLE
Pin screen update bug!!!!

### ISSUE THREAD

**Issue by ramab1988** [MiniKeePass/MiniKeePass#378]
After the recent pin screen update for iPhone app, my pin (4 digit password) is not getting accepted even though it is correct. Please fix this bug as soon as possible. This is not allowing me to access passwords at all l!!!!

iPhone: 5
iOS version: 8.3
MiniKeePass version: 1.6 (latest)

**Comment by Adam001** [comment]
New screen does not allow alpha characters - that's my password!  Can't get in!

**Comment by jarush** [comment]
@Adam001 - The PIN screen is for the PIN option, which has always been a 4-digit numeric code.  It is not the same as your kdb/kdbx password.  Do you recall if you did not have the PIN feature enabled?

**Comment by Adam001** [comment]
I changed the password (or PIN?) on MiniKeePass a while ago when I 
discovered I could indeed set a PIN/PW with 4 letters instead of 4 
digits Î had used before - much more secure!  When I would tap on the 
iPad icon, it asked for the 4 character PW and I would give the 4 letters.

But since the new update today when I tap on the icon it only gives the 
option to enter digits.  I tried the 'old' 4 digit PW/PIN that I 
previously used and that does not work.  I am locked out of the database!

I don't recall any separate PIN feature that was enabled or disabled.

Any ideas for access?

Thanks!

**Comment by Adam001** [comment]
All OK. I removed the App from the iPad, and then downloaded it again.  
The 'new' version did not require a PIN, so I could get in and 
re-download the original KDB file from my PC.

I apparently did have the PIN feature enabled before.   But I was indeed 
able to change the PIN from 4 digits to 4 letters on the old version, 
even though it was not at first obvious that one could do this!

  4 digit PINs are pretty easy to break!

**Comment by jarush** [comment]
Version 1.6.1 is in the store now and addresses this issue, as well allows for arbitrary length alphanumeric PINs using the new "A-Z" button on the PIN screen.

**Comment by Adam001** [comment]
On 6/26/2015 3:50, Jason wrote:
>
> Version 1.6.1 is in the store now and addresses this issue, as well 
> allows for arbitrary length alphanumeric PINs using the new "A-Z" 
> button on the PIN screen.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/MiniKeePass/MiniKeePass/issues/378#issuecomment-115477924>.
>
Thanks, Jason!

Adam

**Comment by jarush** [comment]
@ramab1988 are you still having issues with your PIN?

**Comment by ramab1988** [comment]
Unfortunately, even in the latest release it was still appearing. My 4 digit pin was not getting accepted  in the starting screen :(
I deleted the app (lost all the data), reinstalled and again manually filled all the fields to bring to back to normal state. 

Could you please make sure that these type of critical bugs do not appear in future releases. In fact,  I decided not to upgrade the app because of such nasty bugs. I love the app, but i can't afford to lose all my data. I realized that I could take backup n stuff. Unfortunately, I had not taken and paid the price.

**Comment by jarush** [comment]
To clarify, was your pin all digits, or did you have a combination of letters/digits/etc like Adam001?

I'm sorry you ended up loosing your database file. The app was beta-tested with about 20 people for a couple months without any reports similar to this issue.

**Comment by ramab1988** [comment]
Pin was 4 digits

iPhone: 5
iOS version: 8.3
MiniKeePass version: 1.6
