### ISSUE TITLE
Close Database on Timeout not working?

### ISSUE THREAD

**Issue by tschwartzman** [MiniKeePass/MiniKeePass#379]
Just upgraded to iphone 6.  cannot get minkeepass to immediately lock when i switch away from it, even though i have "Close Enabled" set to true, and "Close Timeout" set to immediately.

Am I missing something?

![img_1546](https://cloud.githubusercontent.com/assets/5853345/8162429/22c1c3a4-134b-11e5-888c-943da1b4887e.PNG)

**Comment by tschwartzman** [comment]
can't explain why but it is working okay now.  it was definitely not locking on losing focus, but seems to be now.  closing this.

**Comment by tripplet** [comment]
The close timeout is not working on my iPhone 5 - iOS 8.3
I reproduced this serveral times and MiniKeePass always keeps the file unlocked.

**Comment by jarush** [comment]
@tripplet - what timeout do you have it set to? I was just testing, and 30s worked for me.

**Comment by tripplet** [comment]
Sorry, I missed your response, the problem is definitly there: Screen capture from my iPhone5:
https://www.dropbox.com/s/5k6anvmdqycmi5z/minikeepass.mov?dl=0

**Comment by jarush** [comment]
Good catch @tschwartzman, I had probably only tested it with the PIN enabled.  I fixed this issue in commit 8144cd10451f103919948d6298efee34e9b45c14.

**Comment by tschwartzman** [comment]
credit to @tripplet for digging into the code.  i wonder if mine now works because I put in a pin then disabled the pin.  regardless good that it is fixed - how does this flow into the apple app store?
