### ISSUE TITLE
Bypass Pin Screen possible

### ISSUE THREAD

**Issue by wolle-xa** [MiniKeePass/MiniKeePass#380]
I' ve today updated to the latest version and now it is possible to bypass the Pin-Screen.
I open the app then pressing the home button, so minikeepass goes into the background.
Then open the app again and voila the database could be openend without the Pin.
If have activated secure thing in the settings.

Minikeepass 1.6
Iphone 4
IOS 7.1.2

Thank you for looking into this issue

**Comment by jarush** [comment]
Someone reported this issue along with a problem with TouchID in #377.  We should be submitting the fix to Apple really soon.  We're just making sure the issue is fixed.

**Comment by marcoanonimo** [comment]
This update introduce the login with Touch ID. 
Good very well done, but unfortunately this has introduced a big bug that allow to pass through the PIN or Touch ID authentication. How to reproduce:
1. Go to setting of the app and put the 'Lock Timeout' to 30 seconds 
2. Close the app and wait longer than 30 seconds
3. Reopen the app and cancel Touch ID authentication (if is enabled in the setting) or click on the home button (if Touch ID is not enabled in the setting)
4. Now you are logged in without the PIN or Touch ID

The problem does not occur if in the setting of the app the 'Lock Timeout' is immediately.

Please fix this major and critical bug, thanks!
Marco

Minikeepass 1.6
Iphone 5S
IOS 8.2

**Comment by jarush** [comment]
Version 1.6.1 is in the store now and addresses this issue, as well allows for arbitrary length alphanumeric PINs using the new "A-Z" button on the PIN screen.
