### ISSUE TITLE
PIN screen doesn't work with letters

### ISSUE THREAD

**Issue by jbalmeida** [MiniKeePass/MiniKeePass#381]
My PIN had 4 letters. With last update to 1.6 couldn't login with PIN screen. I was in panic... Fortunately I was saved by the bug already detected (in #380), so this way I could access to the database without any problem.

But it would be interesting if PIN screen could enable letters or a mix with numbers. At least letters are there as in a phone, but not accessible!...

Any future solution for this?

Thanks.

**Comment by jarush** [comment]
We're working on a fix...  Until we started hearing about people not being able to enter letters today, we didn't even realize that it was possible.  Is it a feature of the iPad or an external keyboard that let you enter letters instead of numbers on the PIN screen?  We were under the impression the keyboard would only display numbers.

**Comment by jbalmeida** [comment]
Hi Jason

As you can see iPhone/iPad keyboard displays both numbers and letters, pressing ABC or 123:




Julio Biscaia 
(Enviado do meu iPad)

No dia 16/06/2015, às 01:04, Jason <notifications@github.com> escreveu:

**Comment by jarush** [comment]
The old pin screen on my device would only let me enter numbers. Never letters.

**Comment by jbalmeida** [comment]
On my iPad with iOS 8.3 it was possible to enter letters as well. I didn't try that with my iPhone 4 with iOS 7.1.2

Julio Biscaia 


No dia 16/06/2015, às 20:53, Jason <notifications@github.com> escreveu:

**Comment by plocki** [comment]
I have the same problem. I can not type a PIN. To provide a PIN keypad contains only digits. How to deal with this problem? Sorry for my english.
(iPad Mini Retina)
LeszekR

**Comment by jarush** [comment]
We submitted a fix to Apple that allows you to enter a alpha-numeric password of an arbitrary length for the PIN.

@plocki - Until that's approved, there's a bug with the new PIN screen that may let you bypass the PIN depending on your settings. Open the app, when prompted for the PIN, double tap home button to show the app switcher, then select the app again. Depending on your PIN settings, this will let you into the app with the current version.

**Comment by plocki** [comment]
Hi
After the last update (2015-06-24) I still can not give your PIN to log in.
What to do? Still wait?

**Comment by jarush** [comment]
There's a "A-Z" button in the lower left of the pin keypad that you should allow you to enter a PIN with letters, numbers, symbols, and PINs longer than 4 digits.

**Comment by plocki** [comment]
The first thing I can see button"A-Z"
![image](https://cloud.githubusercontent.com/assets/12911005/8427080/0917cbe4-1f15-11e5-8684-13507928de2f.jpg)
But, when I type the "A-Z" button, passcode windows appears.
![image](https://cloud.githubusercontent.com/assets/12911005/8427119/69bf2352-1f15-11e5-9d57-ec114e9bb964.jpg)
The program turning me back do login window after password typing.
I can type only the numbers, if I try to push "A-Z" button the program is turning me back to the login window constantly.
When the system will be improved, or how to log-in in the alternative way.

**Comment by jarush** [comment]
So it looks like the new passcode view is popping up, but it sounds like it's not accepting your passcode/PIN? When you enter your passcode, does the original screen say anything (incorrect pin, etc.)?

Anyone else that had a non-numeric PIN containing have this issue?
