### ISSUE TITLE
Not prompting for TouchID

### ISSUE THREAD

**Issue by eademariajr** [MiniKeePass/MiniKeePass#382]
On iPhone 6+, OS 8.3. The MiniKeePass v1.6 update was just applied. TouchID shows 'Enabled' in the app settings, however it's shaded out (cannot change). I don't show the app in the iPhone settings for TouchID and Passcode under 'Use TouchID for:'. I've re-booted the iPhone for possible correction without any luck. Suggestions?

**Comment by wooster11** [comment]
Do you have "PIN Enabled" set to on? It's required in order to enable Touch ID. Touch ID is used for unlocking the app via a PIN and not Database unlocking.

**Comment by eademariajr** [comment]
So . . . Additional level of security is TouchID with a backup or alternate of a PIN and still need password and/or keyfile for the database. That's the way it appears to be working. Is that correct?

**Comment by jarush** [comment]
Correct. PIN (w/ TouchID) is just to lock the app itself.

**Comment by eademariajr** [comment]
Thanks for the clarification!
