### ISSUE TITLE
XARA Attack on miniKeePass MasterPassword possible!?

### ISSUE THREAD

**Issue by DrFrankBV** [MiniKeePass/MiniKeePass#383]
I think using the devices keychain on IOS can make miniKeePass vulnerable to XARA attacks.
Can you please urgently investigate if this is the case and implement some workaround to reduce the risk. As far as I understood there are some possible counter measures especially for the attacks on the keychain.

The risk here, to my understanding, is that a hostile app can get access to the master password of the keyfile (aka epic fail).

More info: https://drive.google.com/file/d/0BxxXk1d3yyuZOFlsdkNMSGswSGs/view?pli=1

**Comment by jarush** [comment]
My understanding from reading a couple of online articles is that the XARA vulnerabilities are actually a few vulnerabilities found between OSX and iOS.  It looks like the vulnerabilities on iOS are limited to URL scheme hijacking, where the keychain access issues are found on OSX.

MiniKeePass doesn't use URL schemes, so it shouldn't be effected by the URL scheme hijacking issue.
