### ISSUE TITLE
Database is no longer locked when "close timeout" expires! (after last app update)

### ISSUE THREAD

**Issue by volker70** [MiniKeePass/MiniKeePass#384]
I am using MiniKeePass version 1.6.
It seems to me that after the last app update (including adding TouchID support) the behaviour of the lockout functionality has changed: The "close timeout" does no longer work! To me this is a big security issue.
My use case: I am not using the PIN and thus PIN protection is not activated in my configuration. Instead I always enter the master passphrase every time I want to unlock MiniKeePass. I have set a "close timeout" of 2 minutes in MiniKeePass. This allows me to lock my iPhone 5S with the standby key; iOS8 then locks the device immediate and my passwords are safe (I have a long alphanumerical device passphrase). However, I can still unlock the again via TouchID, and if the 2 minutes grace period ("close timeout") have not passed yet, then I can - after unlocking the device with TouchID - use MiniKeePass without further authentcation. Which means I do not have to enter the long master passphrase again, should I need to access MiniKeePass once more within those 2 minutes. That works fine for me. However, I rely on the fact the, should I leave the device for more than 2 minutes, MiniKeePass will lock. What I observe now, however, is:
1.) After more than 2 minutes, I can unlock the device using TouchID and then I'm still logged in to MiniKeePass! Which means: Should anybody steal my fingerprint or be able to enter my long device passphrase, then he is also into MiniKeePass. This is definitely not what I want!
2.) I'm not absolutely sure, but to me it seems that the iPhone does not load the battery as long as MiniKeePass is still open in the background. I have to quit MiniKeePass (or at least close the database) in order to be able to load the battery.

**Comment by Thomrima** [comment]
I have exactly the same issue, after the last update, the database timeout won't work. (iPhone 5s, iOS 8.3, MiniKeePass 1.6). Hope you can fix this, it is important for me.
Thanks

**Comment by jarush** [comment]
Interestingly, I've tried to replicate this issue and it always seems to work on my iPhone.

Is there any additional details anyone can provide that may be unique to their usage of the app. For example, does it not work every time? Only if you leave it open on a certain screen?

If able, could you also provide me the values for the following settings:
* PIN Enabled
* (PIN) Lock Timeout
* Close Enabled
* Close Timeout
* Remember Database Passwords

**Comment by Finke3** [comment]
Hi Jarush, 

I have the same problem since update to 1.6.
With disabled Pin code, the close timeout does not work. The database will be closed immediately after switching to another app instead of the configured value (30 seconds). Furthermore I can see the last open minikeepass screen in multitasking view (double clicking the home button) after leaving the app. After switching back to the app, the database has been closed immediately.
Normally I should only see the closed database in multitasking view after switching the app (latest after close timeout). This is a big security issue I think and needs an update asap.
With enabled pin code everything works fine from my side (close timeout and multitasking view shows white screen).

My configuration: 
  
    PIN Enabled (false)
    (PIN) Lock Timeout (immediately)
    Close Enabled (true)
    Close Timeout (30 seconds)
    Remember Database Passwords (false)

Regards 
Finke

**Comment by jarush** [comment]
I believe I have a fix for this issue. The close database option uses some of the same information as the PIN screen for determining if it should close the database (or lock the screen in the case of the PIN).  If the PIN screen wasn't enabled though (which I had tested it with it enabled) the close database option wouldn't work correctly.

I'll upload a new build to Apple with the fix, and it'll probably take about a week or so to show up on the App Store.

**Comment by Finke3** [comment]
Sounds good. Thank you very much for this fix.

**Comment by volker70** [comment]
Sorry for answering a bit late, I'm new to GitHub.
Good news, jarush - I'm looking forward to the fix!
So - just for the records: My problem (close timeout does not lock out the user after the timer is up) is still there with MiniKeePass 1.6.1. My configuration:
a) iPhone 5S with iOS 8.3 (12F70), MiniKeePass 1.6.1, PIN enabled: false, PIN lock timeout: immediately, Close enabled: true, Close timeout: 2 mins, remember database passwords: false
b) iPad4 with iOS 8.3 (12F69), MiniKeePass 1.6.1, PIN enabled: false, PIN lock timeout: immediately, Close enabled: true, Close timeout: 1 mins, remember database passwords: false
The bug is there on both devices, i.e. when I open another application (sending MiniKeePass to background), wait for the lockout time to pass, and then switch back to MiniKeePass, the database is not locked.
My second problem (battery does not load) did not show up anymore - must have been another reason. We can consider it closed for MiniKeePass.

**Comment by Finke3** [comment]
@volker70 : The same problem has happen on my iPhone 6 some days ago. I turned Pin protection on and off again, which fixed the problem on my phone. Maybe you can try this as well? But of course that's another bug which I did not mention in my post above.

**Comment by volker70** [comment]
@Finke3: Great tip - now it works for me, too! Thank you!
I had to do the following (simply switching PIN on and immediately off again did not solve the problem): Enable the PIN (I left TouchID enabled as by default), send MiniKeePass to background, then switch back to MiniKeePass - and unlock via TouchID. Then switch off PIN. Send MiniKeePass to background, wait for the lockout time to pass - and when I then switched back to MiniKeePass, the database was locked.
However - the old contents of the screen (iOS screenshot functionality?) showed up for a very short time. Which can also be a username/password combination. Seems like MiniKeePass still has to blank the screen before entering suspend mode. But I guess this issue is already listed elsewhere.

**Comment by jarush** [comment]
The workaround mentioned by @Finke3 will cause the database to be closed immediately when the app resumes every time. It's the result of a bug in 1.6.1 where the app only records the last time the app exited if the PIN screen is enabled.

When Apple approves 1.6.2, it should fix this problem as well as hides the contents of MiniKeePass from the application switcher when close database is enabled (similar to how the PIN screen works).

**Comment by jarush** [comment]
1.6.2 was approved by Apple today, and the update should be available in the App Store.

**Comment by Finke3** [comment]
Thank you very much. Everything fine from my side.

**Comment by volker70** [comment]
From my side as well: Everything works fine now. Thank you very much!
