### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by yiwesi** [MiniKeePass/MiniKeePass#386]
With the last update 1.6.1 the App crash on start and can't be used.
iPhone 4
iOS 7.1.2

**Comment by yiwesi** [comment]
App still crash on app start with new update 1.6.2 on iPhone 4 with iOS 7.1.2

**Comment by jarush** [comment]
We haven't had any other reports of a startup crash, maybe it's related to iPhone 4/iOS 7. If you can send me the crash report I might be able to discover why it's happening. You can use the following instructions for getting a crash report off your iPhone:
https://developer.apple.com/library/ios/qa/qa1747/_index.html

**Comment by yiwesi** [comment]
Hello,
thank you for your answer.
Strangely, there was no crash report for minikeepass. So I have deleted the app, restart the iPhone and reinstalled the app. Now it works again.
Thanks anyway for your help.

**Comment by jarush** [comment]
Not sure what happened, but I'm glad everything is working again.
