### ISSUE TITLE
Using minikeepass with safari

### ISSUE THREAD

**Issue by Marsfan** [MiniKeePass/MiniKeePass#399]
I turned off the integrated browser function built into mini keepass, but when it opens in safari, there is no way to enter passwords in Safari. I am missing something

Also, can I use mini keepass with chrome instead of safari.

**Comment by puglios** [comment]
In MiniKeePass open the database entry of your interest and just tap the field you want to use: this copies the value into the clipboard, than you can paste it anywhere you want. To enter the password, just tap of the password field in MiniKeePass before opening the URL, then paste the value as usual in Safari.

**Comment by Marsfan** [comment]
@puglios I am aware of that, but I would like to see an extension like 1password has on ios.

**Comment by azetilov** [comment]
This feature is already being developed under another issue - https://github.com/MiniKeePass/MiniKeePass/issues/335
Please, close this one as duplicate.

**Comment by Marsfan** [comment]
Closed as duplicate
