### ISSUE TITLE
No option to load file from Dropbox since latest update

### ISSUE THREAD

**Issue by PatrickRyder** [MiniKeePass/MiniKeePass#410]
Hi,

I realise this is has already been reported, but it is so serious I thought I would raise it again.

With the latest Dropbox and MiniKeePass, I am unable to get a database from Dropbox.  There is no option in Dropbox to send the file to MiniKeePass, which is what the instructions say to do.

Is there a manual workaround until this is fixed?

- Patrick

**Comment by raaphorst** [comment]
Same issue here. Can't share my .kdbx from my MacBook Pro using MacPass to my iPhone using MiniKeePass.

**Comment by raaphorst** [comment]
Does work though if you mail the file to your iPhone. I guess it's Dropbox related.

So got it working now. Manually syncing using email :D

**Comment by azetilov** [comment]
Do you still experience this issue? I can see the 'Copy to MiniKeePass' button.

**Comment by raaphorst** [comment]
Thanks. Works fine now.

**Comment by PatrickRyder** [comment]
Hi,


Thank you for following this up.  I can now find the button.  Sorry for not marking the problem solved.  Hope I haven't wasted too much of your time.




Kind wishes - Patrick Ryder

Author of 'Spiders in Your Mind', a collection of new short stories for those of you who like a scare and 'Crossed Shadows', a novel unlike any you will have read before.  A bold claim, I know.
'Crossed Shadows' available at Amazon: http://goo.gl/48d7LD.<http://goo.gl/48d7LD>
Crossed Shadows eBook: Patrick Ryder: Amazon.co.uk: Kindle Store
Crossed Shadows eBook: Patrick Ryder: Amazon.co.uk: Kindle Store
Read more...<http://goo.gl/48d7LD>

Remove preview
'Spiders in Your Mind' available at Amazon: http://www.amazon.co.uk/Patrick-Ryder/e/B00ANLOWR8/ref=ntt_athr_dp_pel_pop_1.
All other e-reader formats??available (e.g. Nook) at Smashwords: http://www.smashwords.com/profile/view/PatrickRyder
Also available in Apple iStore and Barnes & Noble.
My work is free for members of the armed forces. I also have some free copies to give away. Please drop me a line if you would like one. I'd love to hear from you anyway.




________________________________

**Comment by azetilov** [comment]
Please, close this since no longer an issue
