### ISSUE TITLE
Password Recovery

### ISSUE THREAD

**Issue by jlziegler98** [MiniKeePass/MiniKeePass#411]
I just upgraded from an iPhone 5 to an iPhone 6. I did a cloud backup and everything went well. However, on my iPhone 5, I was not using a password to access MiniKeePass. Upon launching the app on my new iPhone 6 I am prompted to enter a password to access my password database. Having never used a password with MiniKeePass before, I am at a loss as to how to bypass this screen and get to my passwords. Please help.

**Comment by jarush** [comment]
All databases require a password that is used to encrypt/decrypt the database. When you created the database you had to enter a password. Your options probably had MiniKeePass remembering your passwords for you in a secure keychain. This option meant you didn't have to enter the password every time you opened the database.

Your best bet is to try any passwords you may have used in the past to see if you can find the password that was used to encrypt your database. There's no other way of recovering your password.

**Comment by jlziegler98** [comment]
Would this password be numbers or letters? That might help me narrow it down.

**Comment by jarush** [comment]
It could have been any character you can type on the keyboard (numbers, letters, symbols, etc.)
