### ISSUE TITLE
A MiniKeePass Android Version

### ISSUE THREAD

**Issue by EchoEkko** [MiniKeePass/MiniKeePass#412]
Hi all,

Apologies if I am posting this in the wrong category/section (I'm a rookie here). Is there any possibility of having an Android version of MiniKeePass? I'd like to contribute if there is a fundraiser because I am not a developer hence I am not able to contribute with any code. I am a massive fan of this app and it has been a daily driver for me. Plus I'd like to give back to the amazing developers who had transformed litres of coffee into a beautiful useful app. Many thanks.

Jay.

**Comment by littleguga** [comment]
Unfortunately you need to start development of iOS version from 0. iOS sources and Android are not  compatible. So I recommend you to look at Android alternatives of MiniKeePass.

**Comment by mirweb** [comment]
Hi,
I have used [Keepass2Android](https://play.google.com/store/apps/details?id=keepass2android.keepass2android) in my Android Days. Very feature compareable. Also has a offline and a online (to sync with webdav) version. Also [open source](https://keepass2android.codeplex.com/).

Kind regards
