### ISSUE TITLE
Unable to open keepass files on iPad following 1.6.3 update

### ISSUE THREAD

**Issue by rogergau** [MiniKeePass/MiniKeePass#431]
Following the 1.6.3 update on 26th April any attempt to open a keepass file loaded in the MiniKeePass iOS app is unsuccessful. Steps to exhibit this behavior:

1) open MiniKeePass app
2) select one of the existing databases
3) prompts for password. No Key File is selected ("None" shown). None is available for selection. "Key File" line and password entry line are oddly offset/not aligned (UI issue). Unable to proceed because unable to select any key file. Message shows "failed to decrypt".

Have attempted:
1) reloading Keepass databases in to the app
2) deleting and re-installing the app

**Comment by jarush** [comment]
I don't usually use a keyfile with my KeePass database, but when I created a test KeePass database that uses a keyfile on my desktop it opened fine in MiniKeePass.

To clarify, does your KeePass database use:
1. Only a keyfile
2. A master password and keyfile
3. Only a master password

Does your keyfile show up on the main "Files" view that displays when the app opens?

**Comment by rogergau** [comment]
I have 5 different KeePass files which were created on a PC and live in Dropbox. I open them in MiniKeePass from Dropbox on the iOS. Each file has its own master password. The 5 files do show up in the Mini KeePass list of files/databases and when I attempt to open each individually is when I am now having trouble.

I hope that clarifies, happy to explain more if able to.

**Comment by jarush** [comment]
So your KeePass files do not use keyfiles to decrypt the database, only a master password?  If that's the case, you shouldn't see any keyfiles in the list and should leave it set to None.

**Comment by rogergau** [comment]
Only mater passwords. 

It is now working. How embarrassing. I can only guess a combination of incorrect password attempts, perhaps changed UI and timing of the new version lead me up the garden path. In light of your comments trying it again now all files are accessible without problem. 

Sorry to trouble you. Great support!

**Comment by jarush** [comment]
Glad it's working.
