### ISSUE TITLE
touchid to open a kdbx file

### ISSUE THREAD

**Issue by brother** [MiniKeePass/MiniKeePass#462]
I would like to open my kdb(x) files without the need to type my password for the file. I know I can have touchid/pin for the application and so on but I still get prompted about the file password when I open it. Removing the password from the file is not an option as I use it on other devices/computers as well (I sync the file in pydio).

It seems pretty straight forward to have the password two way hashed and then let touchid unlock that and provide it to the kdbx file in the unlock step. No?

**Comment by wooster11** [comment]
Don't remove the password, but rather have MiniKeePass store the password
on your iPhone's keychain.

Settings --> Remember Database Passwords --> Enabled

This is how I do it. MiniKeePass in this way doesn't have to manage your
database password. Rather, the iPhone/iOS does it.

TouchID is used to unlock the App and not your databases. There are plenty
of valid use cases for multiple databases so TouchID per database isn't
really a great option.

**Comment by brother** [comment]
thank you. I know I've seen that option before but I did not make the connection while looking over the settings this time.
This works very good.
