### ISSUE TITLE
DB is asking for password

### ISSUE THREAD

**Issue by cipri78** [MiniKeePass/MiniKeePass#463]
out of the blue one of the kdbx db is asking for a password...it was suppose to save the password, as some others are doing...
any idea if i could get access to it bypassing the password field, which i don't remember?
thanks!

**Comment by tallerthenyou** [comment]
There is one "master" password that is used to encrypt the rest of the password database.
If you had the Remember Database Passwords option set in the settings I'm not sure why it would have forgotten it, but unfortunately there's no way for us to recover that password for you.

It would have been something you picked when you first created the database. There's no harm in trying several passwords, other than that it's time consuming.
