### ISSUE TITLE
Blue words

### ISSUE THREAD

**Issue by burdie123** [MiniKeePass/MiniKeePass#465]
Hello i have with minipass on my ipad blue words, see the image. i can't delete them.  itried also to create a new database but the issue kept.

Has someone a solution
![img_0115](https://cloud.githubusercontent.com/assets/24934076/21675344/e118140a-d331-11e6-8874-bc1786760f2d.PNG)
?

**Comment by TBugReporter** [comment]
Also please take note of [this thread on the KeePass (for PC) forum](https://sourceforge.net/p/keepass/discussion/329221/thread/1e667880/).

**Comment by tallerthenyou** [comment]
This is going to be addressed in a future release. It's fixed in the autolayout branch, but there's a lot of testing to do before we're ready to ship it.
Thank you for reporting this.
