### ISSUE TITLE
PIN screen does not work under iOS 11.0 (beta)

### ISSUE THREAD

**Issue by new-issue** [MiniKeePass/MiniKeePass#497]
With activated PIN there is only an empty screen under iOS 11.0 (beta).

![img_4488 1](https://user-images.githubusercontent.com/30736120/28987126-478054d0-796a-11e7-8683-78ab96d2afdd.PNG)

**Comment by tallerthenyou** [comment]
I just tested this against the iOS 11 GM and I'm not seeing that behavior.

Are you still seeing it?

**Comment by new-issue** [comment]
Sorry, I'm not able to reproduce this behavior with 1.6.3 (store) and iOS 11.0 (final).

**Comment by tallerthenyou** [comment]
Glad to hear that it was resolved. Thanks for reporting it anyway.
