### ISSUE TITLE
Export from dropbox converts filename to lower case

### ISSUE THREAD

**Issue by arvidjaar** [MiniKeePass/MiniKeePass#505]
I have mixed case database name and matching keyfile. Since recently when exporting database file from dropbox it is converted to lowercase in MiniKeePass which means keyfile is not automatically chosen. For now I just renamed everything to lower case, but it somehow does not feel right.

**Comment by tallerthenyou** [comment]
It looks like Dropbox is renaming the file before it gets to us, so there's nothing we can do.

When exporting from Dropbox to iCloud Drive the name is also forced to all lowercase, but when exporting a mixed case file from iCloud Drive to MiniKeePass the filename is not modified at all.
