### ISSUE TITLE
there is no database search in version 1.7

### ISSUE THREAD

**Issue by alexey3f** [MiniKeePass/MiniKeePass#516]
Hello! The same problem with the version 1.7 on the iPhone 6 iOS 10.3.3 - missing the search for the database! Please return the search as soon as possible. It is not possible to use the program!

**Comment by 0x7fh** [comment]
The search is also absent on iOS 11.

**Comment by alexey3f** [comment]
when will it be possible to search the database?

**Comment by nakedpony** [comment]
+1, no search box at the top

**Comment by timmost** [comment]
+1

**Comment by jarush** [comment]
Duplicate of issue #509, please use that issue to track progress.

**Comment by alexey3f** [comment]
Many thanks for your promptness. now everything works fine.
