### ISSUE TITLE
Opening a KDBX causes a crash 

### ISSUE THREAD

**Issue by Bollekes** [MiniKeePass/MiniKeePass#522]
After typing the password to open my existing .kdbx, used with the prevoius version, the app crashes.
Tried 2.x format and 2.34 Old Format. Exporting the KDB to v1.x on the PC with KeePass 2.36 will open.
Version 1.7 IOS 10.3.3 Iphone SE

**Comment by eagle165** [comment]
New update will not let you open a data file which has any data in it.

**Comment by hcarrega** [comment]
So it’s useless

**Comment by starfotograf** [comment]
I had the same problem. xporting the KDB to v1.x on the PC with KeePass 2.36 will open, but I found no search button.

**Comment by rrremedio** [comment]
Same here

**Comment by Erreu** [comment]
It might be related to an entry with a blank title? https://github.com/MiniKeePass/MiniKeePass/issues/537#issuecomment-333430017

**Comment by jarush** [comment]
Thanks for reporting this issue.  We're currently tracking it in issue #526.  We will try and get 1.7.2 in the app store soon, and if that doesn't fix it please open a new issue.
