### ISSUE TITLE
Cannot change the Name from the Database. 1.7

### ISSUE THREAD

**Issue by Caddode** [MiniKeePass/MiniKeePass#525]
I changed normally the name After Import. In 1.7 Not possible

**Comment by whorfin** [comment]
To explain further:
Before 1.7, you could select Edit, then touch the key file instead of delete icon.
That would open a dialogue to rename the key file 
In 1.7 this no longer appears to work

**Comment by jarush** [comment]
You can swipe left in the file to rename.

**Comment by whorfin** [comment]
Thanks 
Saw the red delete and didn’t go further but I now see it’s there if you’re careful not to swipe too far

**Comment by Caddode** [comment]
Solved
