### ISSUE TITLE
Can’t search as of version 1.7

### ISSUE THREAD

**Issue by ShaneSparkyYYZ** [MiniKeePass/MiniKeePass#528]
Upon opening the app I cannot search at all inside the app as of version 1.7

**Comment by jarush** [comment]
Duplicate of issue #509, please use that issue to track progress. A fix has already been submitted to the AppStore for review.

**Comment by ShaneSparkyYYZ** [comment]
Thanks! Sorry I’m new to github, should’ve searched my bad.
