### ISSUE TITLE
build instructions?

### ISSUE THREAD

**Issue by tessus** [MiniKeePass/MiniKeePass#530]
I've been trying to compile the current master and I got stuck right away.
(I did initialize the submodule.)

The first error was 

```
Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
```

I did the `convert to current swift syntax`, but this didn't do anything. Then, after I changed the `Use Legacy Swift Language Version` from `Unspecified` to `No`, I got 3 other errors:

```
MiniKeePass/MiniKeePass/Group View/GroupViewController.swift:63:18: Value of type 'UINavigationItem' has no member 'largeTitleDisplayMode'
```
I've ommited the other 2 errors, but it seems that the parts with

```
if #available(iOS 11.0, *) {
```

error out.

I'm using Xcode Version 8.2.1 (8C1002) on OSX 10.11.6.

Can you please provide some information on how to compile it?

**Comment by tessus** [comment]
found a workaround (commenting the above mentioned 3 `if` occurences).

Still, build instructions would be very helpful.

**Comment by tssmith7** [comment]
I think you need Xcode 9.0 for this to compile correctly.  It did for me.

**Comment by tessus** [comment]
Ok, that is a problem, because I can't install Xcode 9 on El Capitan, and I can't upgrade to a newer OS either.
