### ISSUE TITLE
option 'Search for Title only' - would you accept PR?

### ISSUE THREAD

**Issue by tessus** [MiniKeePass/MiniKeePass#532]
Would you accept the following PR?

- additional switch below Sorting
- name: Searching
- default value off
- text: Search restricted to Title

Since the default is off, current users wouldn't experience a change in behaviour.

But as I've mentioned in https://github.com/MiniKeePass/MiniKeePass/issues/509#issuecomment-332705382, there are situations where searching all fields _can_ have a negative impact.

I'm asking, because I never coded Swift or for iOS before (I'm a macOS/ObjC guy). If you don't accept such a pull request, I won't waste a few hours getting this done.

Although I hope you will. :-)

**Comment by tessus** [comment]
I have some time tomorrow (Sunday) to work on this. Would you accept such a PR?

**Comment by jarush** [comment]
Yes, that sounds good.

**Comment by tessus** [comment]
Done. Tested it on the simulator and it works as expected.

**Comment by tessus** [comment]
@jarush Have you seen my PR?

**Comment by jarush** [comment]
I’ve seen that you submitted it, but not had a chance to look through the code.

**Comment by tessus** [comment]
No worries. Just wanted to make sure you've seen it. That's all. Cheers.
