### ISSUE TITLE
No "x" (clear) button in input when adding an entry

### ISSUE THREAD

**Issue by degie** [MiniKeePass/MiniKeePass#533]
With reference to comment from [#523](https://github.com/MiniKeePass/MiniKeePass/issues/523#issuecomment-332916891), I see the x button disappeared on title input when adding an entry, which delete "New entry" text.
**MiniKee v1.7**
**iOS 11.0**
[Screenshoot where button disappered](https://www.dropbox.com/s/53cde7qpuk418og/Plik%2029.09.2017%2C%2008%2052%2002.jpeg?dl=0)
[The button like this](https://www.dropbox.com/s/t0p1ka7m6i897rs/Zrzut%20ekranu%202017-09-29%20o%2008.55.23.png?dl=0)

**Comment by tessus** [comment]
what about the other fields?

Should the "x" only be for the title, or for user, password, and URL as well?

**Comment by tessus** [comment]
@jarush ha, ok. I already had a PR in the queue for this - depending on the answer. :-)

**Comment by jarush** [comment]
@tessus I was picking off the easy bugs :)
