### ISSUE TITLE
Missing Search field

### ISSUE THREAD

**Issue by pcoggins** [MiniKeePass/MiniKeePass#535]
Missing search field introduced in v1.7 for iOS. please add back into next release. seach functionality is crucial

**Comment by jarush** [comment]
Duplicate of #509. An update to restore search functionality is in the app store review process.

**Comment by szanon** [comment]
Please add search functionality back. This is one of the most crucial functions.

**Comment by RainbowRisingForce** [comment]
Please, I have the same issue. Search filed is very helpful, could you add again on next release?

**Comment by drc12301** [comment]
Please add search functionality back. I use it frequently.

**Comment by peet21** [comment]
without search-function, minikeepass is worthless
