### ISSUE TITLE
1.7.1 crashes when you search over the hole database

### ISSUE THREAD

**Issue by HauserM2407** [MiniKeePass/MiniKeePass#538]
At first many thanks for fixing the missing search field from v. 1.7 so fast.
Unfortunately, if you want to search over a hole database the programm crashes. If you first open a Folder in the Database, it works fine. 
So itˋs not very comfortable to search in 3 or 4 folders to find a certain, I look forward to the next release - quite relaxed ;)

**Comment by Elenorus** [comment]
because of that I am using a flat list since years..

**Comment by GrayWZ** [comment]
I've reverted back to 1.6.3 after getting strange errors in custom fields.

**Comment by StanoRiga** [comment]
same here. In fact not usable for me anymore with this bug. (iOS 11.0.1, App 1.7.1)

**Comment by tallerthenyou** [comment]
I suspect this is related to #526. If you're still experiencing this after 1.7.2 is released (currently waiting for review) please reopen this issue.
