### ISSUE TITLE
Since iOS11 / 1.7.1 no search feature anymore :(

### ISSUE THREAD

**Issue by Elenorus** [MiniKeePass/MiniKeePass#539]
Since the last update of Minikeepass to 1.7.1 there is no search feature anymore. This is quite a problem, since I have to manage several hundred passwords. And just by scrolling, having no test-substring-search feature like before in the old version, is really difficult and cumbersome.

I am using an iphone 7 with iOS 11.0.1. 

Wolfgang from Germany

**Comment by Elenorus** [comment]
Correction. Just after I posted my item here, I found a hint in the forum, which lead me to delete the app and install it again, then to import the kdbx file again. And now Search is back :-))))

So I am fine.

**Comment by jlk** [comment]
Excellent - thanks for mentioning the delete/re-install @Elenorus! That worked for me as well.
