### ISSUE TITLE
Version 1.7.0 and 1.7.1: Username and server not shown in List

### ISSUE THREAD

**Issue by github-skwoz** [MiniKeePass/MiniKeePass#543]
Since Version 1.7.0 the overview list in a group does not show the username/serverinfo anymore.
As I have many combination of users and servers within the same group, it is almost impossible to find the correct entry.
This picture shows the correct handling in version 1.6.3. The marked info isn't available since version 1.7.0
![nousernoserver](https://user-images.githubusercontent.com/32421644/31053000-064d6dbc-a693-11e7-940b-76a96ecd14cd.jpg)

**Comment by Depechie** [comment]
Yes please adjust this, because I have to many entries with the same name making it now very difficult to actually see which is which.

**Comment by tessus** [comment]
@tallerthenyou I was running a few tests and the list view is not updated when an entry is changed.

e.g. if you change the username or URL of an entry. When you go back to the list of entries, the old username/URL is still shown.

The list of entries seems only to be updated when the Title is changed.
