### ISSUE TITLE
Editing cause crash 

### ISSUE THREAD

**Issue by ZHANGJIAN-alpha** [MiniKeePass/MiniKeePass#545]
App will crash on iPhone 7(iOS 11&iOS 10) as long as trying to edit or add record, and this bug exists in the previous versions too. However, on iPhone 5s or iPad mini 2, everything works properly.

**Comment by Erreu** [comment]
It might be related to a blank title? https://github.com/MiniKeePass/MiniKeePass/issues/537#issuecomment-333430017

**Comment by ZHANGJIAN-alpha** [comment]
@Erreu Oh,thanks for reply. I tried it and ensure that there is no entry left blank but it didn't make any difference.

**Comment by Erreu** [comment]
Which version of MiniKeePass are you using? If you create a new blank database does it crash also?

**Comment by ZHANGJIAN-alpha** [comment]
@Erreu 1.7.1. Creating new database won’t cause crash and editing or add records in the new database won't too.

**Comment by Erreu** [comment]
I think this might be fixed in 1.7.2 https://github.com/MiniKeePass/MiniKeePass/issues/544#issuecomment-333712283 https://github.com/MiniKeePass/MiniKeePass/issues/548#issuecomment-333841332

**Comment by ZHANGJIAN-alpha** [comment]
I have upgraded to 1.7.2 but the bug is still here. I can't edit, new or delete records in the existing database(.kdbx) created with my PC. However everything is OK with the database created by iPhone. There might be some problem with compatibility I guess.

**Comment by Erreu** [comment]
Can you create and upload a new database on the PC that causes the crashes? (That doesn't contain personal information.)

**Comment by ZHANGJIAN-alpha** [comment]
The crashes happened again. I have created a new database and upload to the minikepass on iPhone just as you say but it didn't work.

**Comment by Erreu** [comment]
Sorry, I wasn't very clear. I meant upload to the database here, to github.  That way we can examine it to see what is causing the crashes. Just be sure it doesn't contain private information.

**Comment by ZHANGJIAN-alpha** [comment]
I found that the problem was caused by onedrive. There are three files in the package and one is the original file created by PC and the others are the versions by sync(icloud, ondrive).(I don’t know if you can understand what I say. Sorry for my poor English.)

张 健
ZHANG JIAN
TEL: 18552683060
E-MAIL: zhangjianfx@foxmail.com

发件人: Erreu Gedmon
发送时间: 2017年10月5日 23:13
收件人: MiniKeePass/MiniKeePass
抄送: ZHNAG JIAN; Author
主题: Re: [MiniKeePass/MiniKeePass] Editing cause crash (#545)

Sorry, I wasn't very clear. I meant upload to the database here, to github. That way we can examine it to see what is causing the crashes. Just be sure it doesn't contain private information.

**Comment by ZHANGJIAN-alpha** [comment]
The password is 123456

张 健
ZHANG JIAN
TEL: 18552683060
E-MAIL: zhangjianfx@foxmail.com

发件人: Erreu Gedmon
发送时间: 2017年10月5日 23:13
收件人: MiniKeePass/MiniKeePass
抄送: ZHNAG JIAN; Author
主题: Re: [MiniKeePass/MiniKeePass] Editing cause crash (#545)

Sorry, I wasn't very clear. I meant upload to the database here, to github. That way we can examine it to see what is causing the crashes. Just be sure it doesn't contain private information.

**Comment by vvdimov** [comment]
Any update on this issue?

**Comment by Erreu** [comment]
Hi vvdimov. Unfortunately  ZHANGJIAN-alpha never uploaded a test database.

**Comment by ZHANGJIAN-alpha** [comment]
Sorry, but I have already upload the database through the email.

**Comment by ZHANGJIAN-alpha** [comment]
https://1drv.ms/u/s!AovDaCryTLROga0GKJIDO7I1HJNo7A

**Comment by tssmith7** [comment]
@ZHANGJIAN-alpha I don't see an uploaded database.  Since you are using OneDrive your problem is probably related to issue #571.  See that issue for a workaround until the new version of MKP comes out with a fix.
