### ISSUE TITLE
Editing Entry clobbers custom fields

### ISSUE THREAD

**Issue by tssmith7** [MiniKeePass/MiniKeePass#548]
Editing a standard field in an Entry (Title, Username, etc) clobbers a custom field's data.

Steps:
1. Create an Entry with: Title='MyTitle' and a custom field 'Custom1' = 'cust1_data'
2. Press Done.
2(b) Side Note: if you Navigate back to the group view at this point the TableView incorrectly shows the entry as 'New Entry' still.
3. Press Edit and change Title field to 'MyTitle1'
4. Press Done and custom field data is also changed to 'MyTitle1'.

**Comment by tssmith7** [comment]
Found the bug for this one.  Missing `break` in `case` statement at Line #300 of EntryViewController.m

**Comment by jarush** [comment]
Good catch.  Fixed.
