### ISSUE TITLE
Airdrop isn't working since version 1.7

### ISSUE THREAD

**Issue by gitHubEschi** [MiniKeePass/MiniKeePass#550]
Before updating to version 1.7 I was able to send a kdbx file via Airdrop from my iMac to my iPhone. On my iPhone I was asked to commit receiving the file and then Minikeepass started automatically with opening the new file.
Now when I send the file to my iPhone a dialog appears asking me to load an application from the app store.

Could you please fix this (I hope this is a bug and not a restriction by Apple).

**Comment by mpetersen** [comment]
I have the same problem. When I send the .kdbx file to myself via email, I can open the file without issue.

**Comment by alessandro-giardina** [comment]
Same issue for me. Since 1.7 AirDrop isn't working anymore, asking to installa new APP....

**Comment by mpetersen** [comment]
Seems to be fixed by and iOS update. It woks for me on iOS 11.2.6

**Comment by gitHubEschi** [comment]
Thank you mpetersen.
I can confirm the fix via IOS update. So I will close the issue.
