### ISSUE TITLE
Split screen effect

### ISSUE THREAD

**Issue by 0x7fh** [MiniKeePass/MiniKeePass#556]
Today, I have seen a strange split screen effect.

**Comment by 0x7fh** [comment]
Hmm. I have a screenshot. How can I upload or attach it?

**Comment by 0x7fh** [comment]
Upright format:
![097eb9b4-82b0-4540-bbb5-30178f51fc14](https://user-images.githubusercontent.com/17913311/31328386-21cb90b2-acd5-11e7-9857-ce98083f8529.png)

Landscape forward:
![3bae07e5-9acc-4bbd-a26a-f59690b830a1](https://user-images.githubusercontent.com/17913311/31328387-21dddaec-acd5-11e7-8026-9286b0a42163.png)

**Comment by zek0faws** [comment]
Hi,
maybe related to #513

**Comment by 0x7fh** [comment]
Yep, it is.
