### ISSUE TITLE
How Safe is the .kdbx file in DropBox 

### ISSUE THREAD

**Issue by mactoolsix** [MiniKeePass/MiniKeePass#618]
I'm sure this is encrypted, however I just want to be sure. If I download my database to DropBox for transfer to the iPad or iPhone MiniKeePass, is it safe to leave it in DropBox or should I delete it?

**Comment by milesmcclane** [comment]
It’s very well encrypted as long as your password is very strong. Especially if you use a key as well - kept in a separate place of course. 
I keep mine on Dropbox, but held within a cryptomator container. I keep my key in the same Dropbox account but within a separate cryptomator container. Works well, feels super secure whilst being very accessible.

**Comment by mactoolsix** [comment]
Thankyou for that confirmation and tip about using a cryptomator container.
