### ISSUE TITLE
security issue - db and keyfile access 

### ISSUE THREAD

**Issue by pawel1611** [MiniKeePass/MiniKeePass#63]
hi guys,

great job with minikeepass but i have one doubt. The keepass database and keyfile is stored in a location which can be accessed when you connect iphone with USB to any PC (in my case to PC with Ubuntu). I do not have to provide my pin to iphone. The files can be accessed by anyone who will get access to my iphone. it not really secure solution. Tested on iphone ios 5.0.1 jailbroken.

**Comment by ArTruong** [comment]
Hi All

New Keepass support encrypt with ChaCha20 va Argon2 but I set these security mode then MiniKeepass cannot open database file.
I tried "KeePass Touch" then it works well

Hope to fix
Aries
