### ISSUE TITLE
Existing custom fields do not update after change

### ISSUE THREAD

**Issue by GitBruno** [MiniKeePass/MiniKeePass#659]
1. Create new record with custom field and value
  2. Hit done to save record
  3. Problem editing/updating custom field value (will revert back to original value)

**Comment by jamisonbennett** [comment]
I believe this is handled by an open pull request. See https://github.com/MiniKeePass/MiniKeePass/pull/559.

**Comment by GitBruno** [comment]
I do not experience any crashes but that is indeed what it looks like. Thanks!
